// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title  Groth16Verifier
 * @notice Auto-generated by snarkjs `zkey export solidityverifier`.
 *         This is a PLACEHOLDER that will be overwritten by buildCircuit.sh.
 *         Keeping a minimal interface here so the wrapper compiles.
 */
interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[3] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title  RiskScoreRegistry
 * @notice Stores verified ZK risk-score attestations on-chain.
 *
 *         Flow:
 *         1. Backend computes trust score off-chain (ML on banking + GST data)
 *         2. Generates a zk-SNARK proof via snarkjs (Groth16)
 *         3. Submits proof to this contract
 *         4. Contract verifies proof on-chain via the auto-generated verifier
 *         5. Stores the commitment so investors can query it
 *
 *         Public signals: [valid, threshold, scoreCommitment]
 *         - valid = 1 (circuit enforces score >= threshold)
 *         - threshold = minimum acceptable score
 *         - scoreCommitment = Poseidon(rawScore, salt)
 */
contract RiskScoreRegistry is AccessControl {
    bytes32 public constant SUBMITTER_ROLE = keccak256("SUBMITTER_ROLE");

    IGroth16Verifier public verifier;

    struct ScoreAttestation {
        uint256 scoreCommitment;  // Poseidon(rawScore, salt)
        uint256 threshold;        // minimum score that was proven
        uint256 timestamp;
        bool    verified;
    }

    // SME wallet → latest attestation
    mapping(address => ScoreAttestation) public attestations;

    // Track all attested SMEs
    address[] public attestedSMEs;
    mapping(address => bool) private _isAttested;

    event ScoreAttested(
        address indexed sme,
        uint256 scoreCommitment,
        uint256 threshold,
        uint256 timestamp
    );

    constructor(address _verifier, address _admin) {
        require(_verifier != address(0), "RiskRegistry: zero verifier");
        verifier = IGroth16Verifier(_verifier);
        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(SUBMITTER_ROLE, _admin);
    }

    /**
     * @notice Submit a ZK proof that an SME's score meets the threshold.
     * @param sme       The SME's wallet address
     * @param pA        Groth16 proof point A
     * @param pB        Groth16 proof point B
     * @param pC        Groth16 proof point C
     * @param pubSignals [valid, threshold, scoreCommitment]
     */
    function submitScoreProof(
        address sme,
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[3] calldata pubSignals
    ) external onlyRole(SUBMITTER_ROLE) {
        // pubSignals[0] = valid (must be 1, enforced by circuit)
        require(pubSignals[0] == 1, "RiskRegistry: proof says invalid");

        // Verify the Groth16 proof on-chain
        bool ok = verifier.verifyProof(pA, pB, pC, pubSignals);
        require(ok, "RiskRegistry: proof verification failed");

        uint256 threshold = pubSignals[1];
        uint256 commitment = pubSignals[2];

        attestations[sme] = ScoreAttestation({
            scoreCommitment: commitment,
            threshold: threshold,
            timestamp: block.timestamp,
            verified: true
        });

        if (!_isAttested[sme]) {
            _isAttested[sme] = true;
            attestedSMEs.push(sme);
        }

        emit ScoreAttested(sme, commitment, threshold, block.timestamp);
    }

    /**
     * @notice Check if an SME has a verified score meeting a minimum threshold.
     */
    function isScoreVerified(
        address sme,
        uint256 minThreshold
    ) external view returns (bool) {
        ScoreAttestation memory a = attestations[sme];
        return a.verified && a.threshold >= minThreshold;
    }

    /**
     * @notice Update the verifier contract (e.g. after circuit update).
     */
    function setVerifier(
        address _verifier
    ) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(_verifier != address(0), "RiskRegistry: zero verifier");
        verifier = IGroth16Verifier(_verifier);
    }

    function totalAttested() external view returns (uint256) {
        return attestedSMEs.length;
    }
}
